spring:
  config:
    activate:
      on-profile: k8s

  cloud:
    aws:
      region:
        static: ap-northeast-2
      credentials:
        instance-profile: false

  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SYSTEM_EMAIL}
    password: ${SYSTEM_EMAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

server:
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

logging:
  level:
    root: info
    com.rememberme.dunoesanchaeg: debug

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: 'NULL'

jwt:
  secret: ${JWT_SECRET}

kakao:
  client-id: ${KAKAO_CLIENT_ID}
  admin-key: ${KAKAO_ADMIN_KEY}
  redirect-uri: ${KAKAO_REDIRECT_URI}
  client-secret: ${KAKAO_CLIENT_SECRET}

cookie:
  domain: ${COOKIE_DOMAIN}
  secure: false          
  same-site: Lax         

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGIN}
