apiVersion: v1
kind: Service
metadata:
  name: rememberme-frontend-svc
  namespace: rememberme
  labels:
    app: rememberme-frontend
spec:
  type: NodePort
  selector:
    app: rememberme-frontend
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30180
    protocol: TCP
